function db = init_maintenance_database()
    db = struct();
    
    % ========== 数据偏差型故障 ==========
    
    % 故障代码302 - 使用直接数组方式
    db.code_302 = struct(...
        'fault_type', '数据偏差型故障', ...
        'fault_code', '302', ...
        'fault_name', '零点漂移超过允许范围50%', ...
        'description', '偏差漂移超过了允许范围的一半（±0.75vol%O2）', ...
        'severity', '中等', ...
        'priority', 2, ...
        'maintenance_measures', [
            create_measure(1, '检查传感器表面污染', '10分钟', '清洁布、酒精')
            create_measure(2, '检查采样管路冷凝水', '15分钟', '排水工具')
            create_measure(3, '执行零点校准程序', '30分钟', '标准气体')
            create_measure(4, '检查传感器老化程度', '1小时', '测试设备')
            create_measure(5, '更换传感器模块', '2小时', '备用传感器')
        ]);
    
    % 故障代码303
    db.code_303 = struct(...
        'fault_type', '数据偏差型故障', ...
        'fault_code', '303', ...
        'fault_name', '零点漂移超出允许范围', ...
        'description', '偏差漂移超出允许范围（±1.5vol%O2）', ...
        'severity', '严重', ...
        'priority', 1, ...
        'maintenance_measures', [
            create_measure(1, '立即检查传感器状态灯', '5分钟', '无')
            create_measure(2, '检查供电电压24V DC', '10分钟', '万用表')
            create_measure(3, '紧急执行零点量程校准', '45分钟', '标准气体')
            create_measure(4, '检查传感器参比电极', '1.5小时', '专用检测仪')
            create_measure(5, '立即更换传感器', '2小时', '备用传感器')
        ]);
    
    % 故障代码309-311
    db.code_309_311 = struct(...
        'fault_type', '数据偏差型故障', ...
        'fault_code', '309-311', ...
        'fault_name', '温度调节器失效', ...
        'description', '温度控制超出范围', ...
        'severity', '中等', ...
        'priority', 2, ...
        'maintenance_measures', [
            create_measure(1, '检查温度传感器', '10分钟', '温度计')
            create_measure(2, '检查加热冷却器', '20分钟', '万用表')
            create_measure(3, '校准PID参数', '40分钟', '调试软件')
            create_measure(4, '更换温度传感器', '1小时', '备用传感器')
            create_measure(5, '更换温控模块', '2小时', '备用模块')
        ]);
    
    % 其他故障代码也用相同方式...
    
    % 示例：故障代码101
    db.code_101 = struct(...
        'fault_type', '数据传输中断型故障', ...
        'fault_code', '101', ...
        'fault_name', '系统控制器关停', ...
        'description', '主控制器停止工作', ...
        'severity', '紧急', ...
        'priority', 1, ...
        'maintenance_measures', [
            create_measure(1, '检查主电源保险丝', '5分钟', '万用表')
            create_measure(2, '检查24V电源输出', '10分钟', '万用表')
            create_measure(3, '重启控制器系统', '15分钟', '无')
            create_measure(4, '检查CPU和内存', '30分钟', '诊断软件')
            create_measure(5, '更换控制器主板', '2小时', '备用主板')
        ]);
end

function measure = create_measure(step, action, time, tools)
    measure = struct();
    measure.step = step;
    measure.action = action;
    measure.time = time;
    measure.tools = tools;
end

% 测试
db = init_maintenance_database();
fprintf('测试数据库:\n');
fprintf('故障302措施数量: %d\n', length(db.code_302.maintenance_measures));
fprintf('故障303措施数量: %d\n', length(db.code_303.maintenance_measures));
fprintf('故障309-311措施数量: %d\n', length(db.code_309_311.maintenance_measures));
fprintf('故障101措施数量: %d\n', length(db.code_101.maintenance_measures));