classdef MaintenanceDatabase < handle
    % MaintenanceDatabase - 维护建议数据库类
    % 用于存储和管理故障代码对应的维护措施
    
    properties
        faultDatabase = {};  % 故障数据库
    end
    
    methods
        function obj = MaintenanceDatabase()
            % 构造函数 - 初始化故障数据库
            obj.initializeFaultDatabase();
        end
        
        function initializeFaultDatabase(obj)
            % 初始化故障数据库
            db = {};
            
            % ========== 数据偏差型故障 ==========
            
            % 故障代码302
            db{end+1} = struct(...
                'fault_type', '数据偏差型故障', ...
                'fault_code', '302', ...
                'fault_name', '零点漂移超过允许范围50%', ...
                'description', '偏差漂移超过了允许范围的一半（±0.75vol%O2）', ...
                'severity', '中等', ...
                'priority', 2, ...
                'maintenance_measures', {
                    obj.createMeasure(1, '检查传感器表面污染', '10分钟', '清洁布、酒精');
                    obj.createMeasure(2, '检查采样管路冷凝水', '15分钟', '排水工具');
                    obj.createMeasure(3, '执行零点校准程序', '30分钟', '标准气体');
                    obj.createMeasure(4, '检查传感器老化程度', '1小时', '测试设备');
                    obj.createMeasure(5, '更换传感器模块', '2小时', '备用传感器')
                });
            
            % 故障代码303
            db{end+1} = struct(...
                'fault_type', '数据偏差型故障', ...
                'fault_code', '303', ...
                'fault_name', '零点漂移超出允许范围', ...
                'description', '偏差漂移超出允许范围（±1.5vol%O2）', ...
                'severity', '严重', ...
                'priority', 1, ...
                'maintenance_measures', {
                    obj.createMeasure(1, '立即检查传感器状态灯', '5分钟', '无');
                    obj.createMeasure(2, '检查供电电压24V DC', '10分钟', '万用表');
                    obj.createMeasure(3, '紧急执行零点量程校准', '45分钟', '标准气体');
                    obj.createMeasure(4, '检查传感器参比电极', '1.5小时', '专用检测仪');
                    obj.createMeasure(5, '立即更换传感器', '2小时', '备用传感器')
                });
            
            % 故障代码304
            db{end+1} = struct(...
                'fault_type', '数据偏差型故障', ...
                'fault_code', '304', ...
                'fault_name', '灵敏度漂移超出50%', ...
                'description', '放大漂移超出允许范围的50%', ...
                'severity', '中等', ...
                'priority', 2, ...
                'maintenance_measures', {
                    obj.createMeasure(1, '检查测量池窗片清洁度', '15分钟', '清洁工具');
                    obj.createMeasure(2, '检查光源强度稳定性', '20分钟', '光强测试仪');
                    obj.createMeasure(3, '执行量程标定', '40分钟', '量程气体');
                    obj.createMeasure(4, '检查检测器响应曲线', '1小时', '测试设备');
                    obj.createMeasure(5, '更换检测器组件', '2小时', '备用检测器')
                });
            
            % 故障代码305
            db{end+1} = struct(...
                'fault_type', '数据偏差型故障', ...
                'fault_code', '305', ...
                'fault_name', '灵敏度漂移超出允许范围', ...
                'description', '放大漂移超出允许范围', ...
                'severity', '严重', ...
                'priority', 1, ...
                'maintenance_measures', {
                    obj.createMeasure(1, '停止测量检查报警', '5分钟', '无');
                    obj.createMeasure(2, '清洁所有光学元件', '30分钟', '光学清洁套装');
                    obj.createMeasure(3, '执行完整系统标定', '1小时', '多种标准气体');
                    obj.createMeasure(4, '调整光路对准', '1.5小时', '光路调整工具');
                    obj.createMeasure(5, '更换光源和检测器', '3小时', '备件')
                });
            
            % 故障代码319
            db{end+1} = struct(...
                'fault_type', '数据偏差型故障', ...
                'fault_code', '319', ...
                'fault_name', '磁力测量回路失衡', ...
                'description', '磁力式传感器测量回路信号失去平衡', ...
                'severity', '严重', ...
                'priority', 1, ...
                'maintenance_measures', {
                   obj.createMeasure(1, '检查磁场线圈连接', '10分钟', '万用表');
                   obj.createMeasure(2, '测量磁力传感器输出', '20分钟', '示波器');
                   obj.createMeasure(3, '调节信号调理电路', '30分钟', '调试设备');
                   obj.createMeasure(4, '更换磁力传感器', '1小时', '备用传感器');
                   obj.createMeasure(5, '更换传感器电路板', '2小时', '备用电路板')
                });
            
            % 故障代码320
            db{end+1} = struct(...
                'fault_type', '数据偏差型故障', ...
                'fault_code', '320', ...
                'fault_name', '测定放大偏差过高', ...
                'description', '信号放大器偏差超出正常范围', ...
                'severity', '中等', ...
                'priority', 2, ...
                'maintenance_measures', {
                    obj.createMeasure(1, '检查放大器供电', '10分钟', '万用表');
                    obj.createMeasure(2, '调整放大器零点增益', '25分钟', '示波器');
                    obj.createMeasure(3, '更换运放芯片', '45分钟', '备用芯片');
                    obj.createMeasure(4, '检查信号链路', '1小时', '信号发生器');
                    obj.createMeasure(5, '更换放大器板', '1.5小时', '备用电路板')
                });
            
            % 故障代码309-311
            db{end+1} = struct(...
                'fault_type', '数据偏差型故障', ...
                'fault_code', '309-311', ...
                'fault_name', '温度调节器失效', ...
                'description', '温度控制超出范围', ...
                'severity', '中等', ...
                'priority', 2, ...
                'maintenance_measures', {
                    obj.createMeasure(1, '检查温度传感器', '10分钟', '温度计');
                    obj.createMeasure(2, '检查加热冷却器', '20分钟', '万用表');
                    obj.createMeasure(3, '校准PID参数', '40分钟', '调试软件');
                    obj.createMeasure(4, '更换温度传感器', '1小时', '备用传感器');
                    obj.createMeasure(5, '更换温控模块', '2小时', '备用模块')
                });
            
            % ========== 数据传输中断型故障 ==========
            
            % 故障代码101
            db{end+1} = struct(...
                'fault_type', '数据传输中断型故障', ...
                'fault_code', '101', ...
                'fault_name', '系统控制器关停', ...
                'description', '主控制器停止工作', ...
                'severity', '紧急', ...
                'priority', 1, ...
                'maintenance_measures', {
                    obj.createMeasure(1, '检查主电源保险丝', '5分钟', '万用表');
                    obj.createMeasure(2, '检查24V电源输出', '10分钟', '万用表');
                    obj.createMeasure(3, '重启控制器系统', '15分钟', '无');
                    obj.createMeasure(4, '检查CPU和内存', '30分钟', '诊断软件');
                    obj.createMeasure(5, '更换控制器主板', '2小时', '备用主板')
                });
            
            % 故障代码116
            db{end+1} = struct(...
                'fault_type', '数据传输中断型故障', ...
                'fault_code', '116', ...
                'fault_name', 'Profibus安装错误', ...
                'description', 'Profibus模块安装位置错误', ...
                'severity', '中等', ...
                'priority', 3, ...
                'maintenance_measures', {
                    obj.createMeasure(1, '确认安装位置', '5分钟', '无');
                    obj.createMeasure(2, '重装到X20/X21槽', '15分钟', '螺丝刀');
                    obj.createMeasure(3, '重配通讯参数', '20分钟', '配置软件');
                    obj.createMeasure(4, '测试通讯连接', '30分钟', 'Profibus测试仪');
                    obj.createMeasure(5, '更换Profibus模块', '1小时', '备用模块')
                });
            
            % 故障代码201-209
            db{end+1} = struct(...
                'fault_type', '数据传输中断型故障', ...
                'fault_code', '201-209', ...
                'fault_name', '系统总线连接中断', ...
                'description', '系统总线通讯中断', ...
                'severity', '严重', ...
                'priority', 1, ...
                'maintenance_measures', {
                    obj.createMeasure(1, '检查总线电缆', '10分钟', '无');
                    obj.createMeasure(2, '检查终端电阻', '15分钟', '万用表');
                    obj.createMeasure(3, '更换总线电缆', '30分钟', '备用电缆');
                    obj.createMeasure(4, '检查模块供电', '20分钟', '万用表');
                    obj.createMeasure(5, '更换通讯模块', '1小时', '备用模块')
                });
            
            % 故障代码300
            db{end+1} = struct(...
                'fault_type', '数据传输中断型故障', ...
                'fault_code', '300', ...
                'fault_name', '模数转换器无输出', ...
                'description', 'ADC无新测量值', ...
                'severity', '严重', ...
                'priority', 1, ...
                'maintenance_measures', {
                    obj.createMeasure(1, '检查ADC供电', '10分钟', '万用表');
                    obj.createMeasure(2, '检查模拟输入', '15分钟', '示波器');
                    obj.createMeasure(3, '重置ADC芯片', '20分钟', '复位工具');
                    obj.createMeasure(4, '更换ADC芯片', '1小时', '备用芯片');
                    obj.createMeasure(5, '更换采集卡', '1.5小时', '备用采集卡')
                });
            
            % 故障代码308
            db{end+1} = struct(...
                'fault_type', '数据传输中断型故障', ...
                'fault_code', '308', ...
                'fault_name', '测定值计算错误', ...
                'description', '计算过程错误', ...
                'severity', '中等', ...
                'priority', 2, ...
                'maintenance_measures', {
                    obj.createMeasure(1, '重启处理程序', '5分钟', '无');
                    obj.createMeasure(2, '检查CPU内存', '10分钟', '监控软件');
                    obj.createMeasure(3, '清理系统缓存', '15分钟', '清理工具');
                    obj.createMeasure(4, '重装固件程序', '45分钟', '固件包');
                    obj.createMeasure(5, '更换处理器板', '2小时', '备用板')
                });
            
            % 故障代码318
            db{end+1} = struct(...
                'fault_type', '数据传输中断型故障', ...
                'fault_code', '318', ...
                'fault_name', 'ADC无新测量', ...
                'description', 'ADC无新数据', ...
                'severity', '严重', ...
                'priority', 1, ...
                'maintenance_measures', {
                    obj.createMeasure(1, '检查触发信号', '10分钟', '示波器');
                    obj.createMeasure(2, '检查时钟信号', '15分钟', '示波器');
                    obj.createMeasure(3, '重配采样参数', '20分钟', '配置软件');
                    obj.createMeasure(4, '更换时钟芯片', '45分钟', '备用芯片');
                    obj.createMeasure(5, '更换ADC模块', '1.5小时', '备用模块')
                });
            
            % 故障代码332-337
            db{end+1} = struct(...
                'fault_type', '数据传输中断型故障', ...
                'fault_code', '332-337', ...
                'fault_name', 'I/O板故障', ...
                'description', 'I/O板硬件问题', ...
                'severity', '中等', ...
                'priority', 2, ...
                'maintenance_measures', {
                    obj.createMeasure(1, '检查I/O板指示灯', '5分钟', '无');
                    obj.createMeasure(2, '检查I/O配置', '15分钟', '配置软件');
                    obj.createMeasure(3, '测试I/O通道', '30分钟', '万用表');
                    obj.createMeasure(4, '初始化I/O板', '20分钟', '初始化工具');
                    obj.createMeasure(5, '更换I/O板', '1小时', '备用板')
                });
            
            % 故障代码338-339
            db{end+1} = struct(...
                'fault_type', '数据传输中断型故障', ...
                'fault_code', '338-339', ...
                'fault_name', '模拟线路故障', ...
                'description', '线路断裂或短路', ...
                'severity', '严重', ...
                'priority', 1, ...
                'maintenance_measures', {
                    obj.createMeasure(1, '检查接线端子', '10分钟', '螺丝刀');
                    obj.createMeasure(2, '测量线路通断', '15分钟', '万用表');
                    obj.createMeasure(3, '检查屏蔽接地', '20分钟', '接地测试仪');
                    obj.createMeasure(4, '更换信号电缆', '30分钟', '备用电缆');
                    obj.createMeasure(5, '重新布线', '2小时', '布线工具')
                });
            
            % ========== 数据保持型故障 ==========
            
            % 故障代码301
            db{end+1} = struct(...
                'fault_type', '数据保持型故障', ...
                'fault_code', '301', ...
                'fault_name', '超出ADC阈值', ...
                'description', '超出ADC范围', ...
                'severity', '中等', ...
                'priority', 2, ...
                'maintenance_measures', {
                    obj.createMeasure(1, '确认实际浓度', '5分钟', '便携式分析仪');
                    obj.createMeasure(2, '检查量程设置', '10分钟', '配置软件');
                    obj.createMeasure(3, '调整信号衰减', '20分钟', '调节工具');
                    obj.createMeasure(4, '重选测量量程', '30分钟', '配置软件');
                    obj.createMeasure(5, '更换大量程传感器', '2小时', '备用传感器')
                });
            
            % 故障代码344
            db{end+1} = struct(...
                'fault_type', '数据保持型故障', ...
                'fault_code', '344', ...
                'fault_name', '超上限130%', ...
                'description', '超过量程130%', ...
                'severity', '严重', ...
                'priority', 1, ...
                'maintenance_measures', {
                    obj.createMeasure(1, '检查工艺异常', '5分钟', '工艺参数表');
                    obj.createMeasure(2, '检查空气泄漏', '15分钟', '检漏仪');
                    obj.createMeasure(3, '检查传感器饱和', '20分钟', '测试仪');
                    obj.createMeasure(4, '切换高量程', '30分钟', '配置软件');
                    obj.createMeasure(5, '更换高量程传感器', '2小时', '备用传感器')
                });
            
            % 故障代码345
            db{end+1} = struct(...
                'fault_type', '数据保持型故障', ...
                'fault_code', '345', ...
                'fault_name', '低于下限-100%', ...
                'description', '低于量程-100%', ...
                'severity', '严重', ...
                'priority', 1, ...
                'maintenance_measures', {
                    obj.createMeasure(1, '检查传感器接线', '10分钟', '接线图');
                    obj.createMeasure(2, '检查信号电路', '20分钟', '万用表');
                    obj.createMeasure(3, '验证零点设置', '30分钟', '零点气体');
                    obj.createMeasure(4, '重新标定', '45分钟', '标准气体');
                    obj.createMeasure(5, '更换传感器信号板', '2小时', '备件')
                });
            
            % ========== 数据波动型故障 ==========
            
            % 故障代码312
            db{end+1} = struct(...
                'fault_type', '数据波动型故障', ...
                'fault_code', '312', ...
                'fault_name', '压力修正失效', ...
                'description', '压力测量错误', ...
                'severity', '中等', ...
                'priority', 2, ...
                'maintenance_measures', {
                    obj.createMeasure(1, '检查压力传感器', '10分钟', '压力表');
                    obj.createMeasure(2, '检查压力管路', '15分钟', '检漏仪');
                    obj.createMeasure(3, '校准压力传感器', '30分钟', '标准压力源');
                    obj.createMeasure(4, '检查补偿算法', '20分钟', '配置软件');
                    obj.createMeasure(5, '更换压力传感器', '1小时', '备用传感器')
                });
            
            % 外部因素EXT-01
            db{end+1} = struct(...
                'fault_type', '数据波动型故障', ...
                'fault_code', 'EXT-01', ...
                'fault_name', '管路污染堵塞', ...
                'description', '管道或过滤器问题', ...
                'severity', '中等', ...
                'priority', 2, ...
                'maintenance_measures', {
                    obj.createMeasure(1, '检查过滤器压差', '5分钟', '压差表');
                    obj.createMeasure(2, '更换过滤器', '20分钟', '备用滤芯');
                    obj.createMeasure(3, '吹扫采样管路', '30分钟', '压缩空气');
                    obj.createMeasure(4, '检查管路泄漏', '45分钟', '检漏仪');
                    obj.createMeasure(5, '更换采样管路', '2小时', '备用管路')
                });
            
            % 外部因素EXT-02
            db{end+1} = struct(...
                'fault_type', '数据波动型故障', ...
                'fault_code', 'EXT-02', ...
                'fault_name', '气路扭结泄漏', ...
                'description', '气路系统问题', ...
                'severity', '中等', ...
                'priority', 2, ...
                'maintenance_measures', {
                    obj.createMeasure(1, '检查管路扭结', '5分钟', '手电筒');
                    obj.createMeasure(2, '检查流量', '10分钟', '流量计');
                    obj.createMeasure(3, '逐段检漏', '30分钟', '检漏仪');
                    obj.createMeasure(4, '紧固接头', '20分钟', '扳手');
                    obj.createMeasure(5, '重装气路', '3小时', '全套管路')
                });
            
            % 映射系统内部故障代码到维护数据库
            % 001-满量程输出 -> 344
            db{end+1} = struct(...
                'fault_type', '满量程输出', ...
                'fault_code', '001', ...
                'fault_name', '满量程输出', ...
                'description', '氧浓度值达到或超过满量程阈值', ...
                'severity', '严重', ...
                'priority', 1, ...
                'maintenance_measures', {
                    obj.createMeasure(1, '检查工艺异常', '5分钟', '工艺参数表');
                    obj.createMeasure(2, '检查空气泄漏', '15分钟', '检漏仪');
                    obj.createMeasure(3, '检查传感器饱和', '20分钟', '测试仪');
                    obj.createMeasure(4, '切换高量程', '30分钟', '配置软件');
                    obj.createMeasure(5, '更换高量程传感器', '2小时', '备用传感器')
                });
            
            % 002-零位输出 -> 345
            db{end+1} = struct(...
                'fault_type', '零位输出', ...
                'fault_code', '002', ...
                'fault_name', '零位输出', ...
                'description', '氧浓度值达到或低于零位阈值', ...
                'severity', '严重', ...
                'priority', 1, ...
                'maintenance_measures', {
                    obj.createMeasure(1, '检查传感器接线', '10分钟', '接线图');
                    obj.createMeasure(2, '检查信号电路', '20分钟', '万用表');
                    obj.createMeasure(3, '验证零点设置', '30分钟', '零点气体');
                    obj.createMeasure(4, '重新标定', '45分钟', '标准气体');
                    obj.createMeasure(5, '更换传感器信号板', '2小时', '备件')
                });
            
            % 003-数据缺失 -> 300
            db{end+1} = struct(...
                'fault_type', '数据缺失', ...
                'fault_code', '003', ...
                'fault_name', '数据缺失', ...
                'description', '检测到NaN值或数据中断', ...
                'severity', '严重', ...
                'priority', 1, ...
                'maintenance_measures', {
                    obj.createMeasure(1, '检查ADC供电', '10分钟', '万用表');
                    obj.createMeasure(2, '检查模拟输入', '15分钟', '示波器');
                    obj.createMeasure(3, '重置ADC芯片', '20分钟', '复位工具');
                    obj.createMeasure(4, '更换ADC芯片', '1小时', '备用芯片');
                    obj.createMeasure(5, '更换采集卡', '1.5小时', '备用采集卡')
                });
            
            % 004-数据保持 -> 301
            db{end+1} = struct(...
                'fault_type', '数据保持', ...
                'fault_code', '004', ...
                'fault_name', '数据保持', ...
                'description', '数据值长时间保持不变', ...
                'severity', '中等', ...
                'priority', 2, ...
                'maintenance_measures', {
                    obj.createMeasure(1, '确认实际浓度', '5分钟', '便携式分析仪');
                    obj.createMeasure(2, '检查量程设置', '10分钟', '配置软件');
                    obj.createMeasure(3, '调整信号衰减', '20分钟', '调节工具');
                    obj.createMeasure(4, '重选测量量程', '30分钟', '配置软件');
                    obj.createMeasure(5, '更换大量程传感器', '2小时', '备用传感器')
                });
            
            % 005-剧烈波动 -> 312
            db{end+1} = struct(...
                'fault_type', '剧烈波动异常', ...
                'fault_code', '005', ...
                'fault_name', '剧烈波动异常', ...
                'description', '数据标准差超过正常范围', ...
                'severity', '中等', ...
                'priority', 2, ...
                'maintenance_measures', {
                    obj.createMeasure(1, '检查压力传感器', '10分钟', '压力表');
                    obj.createMeasure(2, '检查压力管路', '15分钟', '检漏仪');
                    obj.createMeasure(3, '校准压力传感器', '30分钟', '标准压力源');
                    obj.createMeasure(4, '检查补偿算法', '20分钟', '配置软件');
                    obj.createMeasure(5, '更换压力传感器', '1小时', '备用传感器')
                });
            
            % 006-数据偏移 -> 302/303
            db{end+1} = struct(...
                'fault_type', '数据偏移', ...
                'fault_code', '006', ...
                'fault_name', '数据偏移', ...
                'description', '数据均值偏离正常范围', ...
                'severity', '中等', ...
                'priority', 2, ...
                'maintenance_measures', {
                    obj.createMeasure(1, '检查传感器表面污染', '10分钟', '清洁布、酒精');
                    obj.createMeasure(2, '检查采样管路冷凝水', '15分钟', '排水工具');
                    obj.createMeasure(3, '执行零点校准程序', '30分钟', '标准气体');
                    obj.createMeasure(4, '检查传感器老化程度', '1小时', '测试设备');
                    obj.createMeasure(5, '更换传感器模块', '2小时', '备用传感器')
                });
            
            obj.faultDatabase = db;
        end
        
        function measure = createMeasure(obj, level, desc, time, tools)
            % 创建维护措施结构
            % 输入验证
            if nargin < 5
                error('需要提供所有必需参数：level, desc, time, tools');
            end
            
            if ~isnumeric(level) || level < 1 || level > 5
                error('维护级别必须在1-5之间');
            end
            
            if isempty(desc) || isempty(time) || isempty(tools)
                error('措施描述、时间和工具不能为空');
            end
            
            measure = struct(...
                'level', level, ...
                'measure', desc, ...
                'time', time, ...
                'tools', tools);
        end
        
        function [fault_info, measures] = getFaultInfo(obj, fault_type, fault_code)
            % 根据故障类型和代码获取故障信息
            % 输入验证
            if nargin < 2
                error('需要提供故障类型参数');
            end
            
            if nargin < 3
                fault_code = '';
            end
            
            if isempty(fault_type)
                error('故障类型不能为空');
            end
            
            fault_info = [];
            measures = {};
            
            % 使用精确匹配而不是contains
            for i = 1:length(obj.faultDatabase)
                if strcmp(obj.faultDatabase{i}.fault_type, fault_type)
                    if ~isempty(fault_code) && strcmp(obj.faultDatabase{i}.fault_code, fault_code)
                        fault_info = obj.faultDatabase{i};
                        measures = fault_info.maintenance_measures;
                        break;
                    elseif isempty(fault_code)
                        % 返回该类型的第一个故障
                        fault_info = obj.faultDatabase{i};
                        measures = fault_info.maintenance_measures;
                        break;
                    end
                end
            end
            
            if isempty(fault_info)
                fprintf('未找到匹配的故障信息\n');
            end
        end
        
        function fault_info = getFaultByCode(obj, fault_code)
            % 根据故障代码直接获取故障信息（新增方法）
            % 输入验证
            if nargin < 2 || isempty(fault_code)
                error('需要提供故障代码');
            end
            
            fault_info = [];
            
            for i = 1:length(obj.faultDatabase)
                if strcmp(obj.faultDatabase{i}.fault_code, fault_code)
                    fault_info = obj.faultDatabase{i};
                    break;
                end
            end
            
            if isempty(fault_info)
                fprintf('未找到故障代码 %s 的信息\n', fault_code);
            end
        end
        
        function displayFaultInfo(obj, fault_info, measures)
            % 显示故障信息和维护建议
            if isempty(fault_info)
                fprintf('没有可显示的故障信息\n');
                return;
            end
            
            fprintf('\n════════════════════════════════════════\n');
            fprintf('           故障诊断与维护建议\n');
            fprintf('════════════════════════════════════════\n');
            fprintf('故障代码: %s\n', fault_info.fault_code);
            fprintf('故障名称: %s\n', fault_info.fault_name);
            fprintf('故障类型: %s\n', fault_info.fault_type);
            fprintf('故障描述: %s\n', fault_info.description);
            fprintf('严重程度: %s\n', fault_info.severity);
            fprintf('优先级: %d\n', fault_info.priority);
            fprintf('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');
            fprintf('维护措施建议:\n\n');
            
            if ~isempty(measures)
                for i = 1:length(measures)
                    fprintf('【级别%d】%s\n', measures{i}.level, measures{i}.measure);
                    fprintf('    预计时间: %s\n', measures{i}.time);
                    fprintf('    所需工具: %s\n\n', measures{i}.tools);
                end
            else
                fprintf('暂无维护措施建议\n');
            end
            
            fprintf('════════════════════════════════════════\n\n');
        end
        
        function displayMaintenanceSummary(obj, fault_codes)
            % 显示多个故障的维护建议汇总
            if isempty(fault_codes)
                fprintf('没有故障需要维护\n');
                return;
            end
            
            fprintf('\n════════════════════════════════════════\n');
            fprintf('           维护建议汇总\n');
            fprintf('════════════════════════════════════════\n');
            
            for i = 1:length(fault_codes)
                fault_info = obj.getFaultByCode(fault_codes{i});
                if ~isempty(fault_info)
                    fprintf('\n【%s】%s - %s\n', fault_info.fault_code, ...
                            fault_info.fault_name, fault_info.severity);
                    if ~isempty(fault_info.maintenance_measures)
                        fprintf('  建议措施: %s\n', fault_info.maintenance_measures{1}.measure);
                        fprintf('  预计时间: %s\n', fault_info.maintenance_measures{1}.time);
                    end
                end
            end
            
            fprintf('\n════════════════════════════════════════\n\n');
        end
    end
end